name: Deploy GitHub Pages

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetli/wasm-pack-action@v0.4.0
      - name: "Move static to pkg"
        run: cp -r ./static/. pkg
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./pkg/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment