name: Deploy GitHub Pages

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Build WASM binary
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Install wasm-bindgen
        run: cargo binstall wasm-bindgen-cli -y
      - name: Generate JS bindings for WASM
        run: wasm-bindgen --browser --out-dir dist ./target/wasm32-unknown-unknown/release/format_conv.wasm
      - name: Copy files from static
        run: cp -r ./static/. ./dist/
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment