name: Deploy GitHub Pages

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - name: Install wasm-pack
        run: cargo binstall wasm-pack -y
      - name: Build using wasm-pack
        run: wasm-pack build --target web --release
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./pkg/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment