name: deploy gh-pages branch

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - run: rustup target add wasm32-unknown-unknown
      - name: Build WASM
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Install wasm-bindgen
        run: cargo binstall wasm-bindgen-cli -y
      - name: Generate JS bindings for WASM
        run: wasm-bindgen --browser --out-dir dist ./target/wasm32-unknown-unknown/release/format_conv.wasm
      - name: Copy files from static
        run: cp -r ./static/. ./dist/
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
      - run: ls -r
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}