name: deploy gh-pages branch

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - name: Install wasm-pack
        run: cargo binstall wasm-pack -y
      - name: Build to WASM/JS
        run: RUST_LOG=info wasm-pack build --target web --out-dir ./dist
      - name: Copy files from static
        run: cp -r ./static/. ./dist/
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: deploy-branch
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
      - run: ls -r
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./